// Generated by wxt
/// <reference types="wxt/vite-builder-env" />
/// <reference types="wxt-module-safari-xcode" />
/// <reference types="./types/paths.d.ts" />
/// <reference types="./types/i18n.d.ts" />
/// <reference types="./types/globals.d.ts" />
/// <reference types="./types/imports.d.ts" />
